Repository hakzzang/Weightlessness, pull requests merged in 2019-08, with the labels that each got.

#2 closed #1 초기 프로젝트 설정
  app/build.gradle
  app/src/main/java/hbs/com/weightlessness/remote/JobCafeRepository.kt
  app/src/main/java/hbs/com/weightlessness/remote/RetrofitProvider.kt
  app/src/main/java/hbs/com/weightlessness/remote/SeoulAPI.kt
  app/src/main/java/hbs/com/weightlessness/remote/model/ApiResult.kt
  app/src/main/java/hbs/com/weightlessness/remote/model/JobCafe.kt
  app/src/main/java/hbs/com/weightlessness/remote/model/JobCafeList.kt
  app/src/main/java/hbs/com/weightlessness/search/SearchContract.kt
  app/src/main/java/hbs/com/weightlessness/usecase/JobCafeUseCase.kt
  build.gradle
Labels: enhancement

#4 closed #3 search ui 구조 분리
  app/src/main/AndroidManifest.xml
  app/src/main/java/hbs/com/weightlessness/ui/EMPTY.kt
  app/src/main/java/hbs/com/weightlessness/ui/search/SearchActivity.kt
  app/src/main/java/hbs/com/weightlessness/ui/search/SearchContract.kt
  app/src/main/res/layout/activity_main.xml
Labels: enhancement

#8 closed #7 CategoryView의 오버뷰 기능 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/hbs/com/weightlessness/remote/JobCafeRepository.kt
  app/src/main/java/hbs/com/weightlessness/remote/RetrofitProvider.kt
  app/src/main/java/hbs/com/weightlessness/remote/SeoulAPI.kt
  app/src/main/java/hbs/com/weightlessness/remote/model/JobCafeList.kt
  app/src/main/java/hbs/com/weightlessness/remote/model/WrappingJobCafeList.kt
  app/src/main/java/hbs/com/weightlessness/ui/home/HomeActivity.kt
  app/src/main/java/hbs/com/weightlessness/ui/home/HomeContract.kt
  app/src/main/java/hbs/com/weightlessness/ui/home/HomePresenter.kt
  app/src/main/java/hbs/com/weightlessness/usecase/JobCafeUseCase.kt
  app/src/main/java/hbs/com/weightlessness/util/BaseContract.kt
  app/src/main/java/hbs/com/weightlessness/util/HomeCategoryAdapter.kt
  app/src/main/java/hbs/com/weightlessness/util/ViewHomeCategory.kt
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/item_home_category.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/network_security_config.xml
  app/src/test/java/hbs/com/weightlessness/ExampleUnitTest.kt
Labels: enhancement

#10 closed #9 UseCase를 DataSource로 작명 변경
  .idea/misc.xml
  app/src/main/java/hbs/com/weightlessness/ui/home/HomePresenter.kt
  app/src/main/java/hbs/com/weightlessness/usecase/JobCafeDataSource.kt
  app/src/main/java/hbs/com/weightlessness/util/ViewHomeCategory.kt
  app/src/test/java/hbs/com/weightlessness/ExampleUnitTest.kt
Labels: 간단간단 코드, 새우버거가 함께합니다.

#12 closed #11 Paging Library 도입
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/assets/skeleton_loading.json
  app/src/main/java/hbs/com/weightlessness/remote/model/JobCafeDataFactory.kt
  app/src/main/java/hbs/com/weightlessness/ui/DataBindingUtils.kt
  app/src/main/java/hbs/com/weightlessness/ui/home/HomePresenter.kt
  app/src/main/java/hbs/com/weightlessness/ui/jobcafe/JobCafeActivity.kt
  app/src/main/java/hbs/com/weightlessness/ui/jobcafe/JobCafeContract.kt
  app/src/main/java/hbs/com/weightlessness/ui/jobcafe/JobCafePresenter.kt
  app/src/main/java/hbs/com/weightlessness/usecase/JobCafeDataSource.kt
  app/src/main/java/hbs/com/weightlessness/util/HomeCategoryAdapter.kt
  app/src/main/java/hbs/com/weightlessness/util/JobCafeListAdapter.kt
  app/src/main/res/drawable/ic_plug.xml
  app/src/main/res/drawable/no_connected_image.xml
  app/src/main/res/layout/activity_jobcafe.xml
  app/src/main/res/layout/item_jobcafe_list.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/hbs/com/weightlessness/ExampleUnitTest.kt
  build.gradle
Labels: TEST, 새우버거가 함께합니다., 초복잡

#14 closed #13 Chatting UI 만들기
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/hbs/com/weightlessness/ui/chat/ChatActivity.kt
  app/src/main/java/hbs/com/weightlessness/ui/chat/ChatContract.kt
  app/src/main/java/hbs/com/weightlessness/ui/chat/ChatPresenter.kt
  app/src/main/java/hbs/com/weightlessness/ui/chat/ChattingAdapter.kt
  app/src/main/java/hbs/com/weightlessness/usecase/JobCafeDataSource.kt
  app/src/main/java/hbs/com/weightlessness/util/AnimationUtils.kt
  app/src/main/res/drawable/bg_home_category.xml
  app/src/main/res/drawable/bg_send_chat_container.xml
  app/src/main/res/drawable/bg_send_chat_off.xml
  app/src/main/res/drawable/bg_send_chat_on.xml
  app/src/main/res/drawable/ic_send_button_off.xml
  app/src/main/res/drawable/ic_send_button_on.xml
  app/src/main/res/drawable/shrimp_burger.png
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/item_chatting_dialog.xml
  app/src/main/res/mipmap-hdpi/ic_your_dialog.9.png
  app/src/main/res/mipmap-mdpi/ic_your_dialog.9.png
  app/src/main/res/mipmap-xhdpi/ic_your_dialog.9.png
  app/src/main/res/mipmap-xxhdpi/drawable-xxhdpi/ic_your_dialog.9.png
  app/src/main/res/mipmap-xxxhdpi/ic_your_dialog.9.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
Labels: 새우버거가 함께합니다., 초복잡

#17 네트워크 security config 개선
  app/src/main/AndroidManifest.xml
  app/src/main/res/xml/network_security_config.xml
Labels: bug, 간단간단 코드, 새우버거가 함께합니다.
